FROM ubuntu:16.04

# This is passed to the heron build command via the --config flag
ENV TARGET_PLATFORM ubuntu
ENV bazelVersion 0.3.1

RUN apt-get update && apt-get -y install \
      automake \
      build-essential \
      cmake \
      curl \
      libssl-dev \
      git \
      libtool \
      libunwind8 \
      libunwind-setjmp0-dev \
      python \
      python2.7-dev \
      python-software-properties \
      software-properties-common \
      python-setuptools \
      zip \
      unzip \
      wget

RUN apt-get clean all

# Install python pip and wheel
RUN easy_install pip
RUN pip install wheel

# Install open jdk
RUN apt-get -y install openjdk-8-jdk; apt-get clean all
ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-amd64

# Install maven for java
RUN apt-get -y install maven; apt-get clean all

# Install nodejs
RUN wget -qO- https://raw.githubusercontent.com/creationix/nvm/v0.33.2/install.sh | bash
RUN cd /root/.nvm && chmod +x nvm.sh && cd .. && . /root/.nvm/nvm.sh && nvm install stable && nvm use stable

# Install hugo for website
RUN wget -q https://github.com/spf13/hugo/releases/download/v0.15/hugo_0.15_amd64.deb
RUN dpkg -i hugo*.deb
RUN hugo version
RUN apt-get install -y nodejs  
RUN apt-get install -y npm
RUN rm -rf hugo_0.15_amd64.deb
RUN apt-get clean all

# Install Google cloud command line utility
RUN echo "deb http://packages.cloud.google.com/apt cloud-sdk-xenial main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
RUN curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
RUN apt-get update && apt-get -y install google-cloud-sdk
RUN apt-get clean all

# Install Google Bazel
RUN wget -O /tmp/bazel.sh https://github.com/bazelbuild/bazel/releases/download/$bazelVersion/bazel-$bazelVersion-installer-linux-x86_64.sh
RUN chmod +x /tmp/bazel.sh && /tmp/bazel.sh
RUN rm -rf /tmp/bazel.sh
RUN touch /root/.bazelrc
RUN bazel version
